"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { createMaintenancePlanAction } from "@/lib/actions";

export function CreateMaintenancePlanForm({
  projects,
  defaultChecklist,
  lockedProjectId,
}: {
  projects: { id: string; name: string; clientName: string }[];
  defaultChecklist: string;
  /** When set (e.g. embedded in a single project's Settings tab), skips the project picker entirely. */
  lockedProjectId?: string;
}) {
  const [open, setOpen] = useState(false);

  return (
    <>
      <Button onClick={() => setOpen(true)}>+ New maintenance plan</Button>

      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle>New maintenance plan</DialogTitle>
            <DialogDescription>A recurring retainer checklist, generated by hand each cycle.</DialogDescription>
          </DialogHeader>
          <form
            action={async (formData) => {
              await createMaintenancePlanAction(formData);
              setOpen(false);
            }}
            className="space-y-3"
          >
            <div className="grid grid-cols-2 gap-3">
              {lockedProjectId ? (
                <input type="hidden" name="projectId" value={lockedProjectId} />
              ) : (
                <select name="projectId" required className="col-span-2 rounded-md border border-black/15 px-3 py-2 text-sm">
                  <option value="">Select project…</option>
                  {projects.map((p) => (
                    <option key={p.id} value={p.id}>
                      {p.name} · {p.clientName}
                    </option>
                  ))}
                </select>
              )}
              <input
                type="text"
                name="name"
                required
                defaultValue="Monthly Maintenance"
                className="col-span-2 rounded-md border border-black/15 px-3 py-2 text-sm"
              />
            </div>
            <label className="block">
              <span className="mb-1 block text-xs font-semibold text-muted-foreground">Cadence (days)</span>
              <input
                type="number"
                name="cadenceDays"
                min={1}
                defaultValue={30}
                className="w-24 rounded-md border border-black/15 px-3 py-2 text-sm"
              />
            </label>
            <label className="block">
              <span className="mb-1 block text-xs font-semibold text-muted-foreground">
                Checklist (one item per line)
              </span>
              <textarea
                name="checklistTemplate"
                defaultValue={defaultChecklist}
                rows={7}
                className="w-full rounded-md border border-black/15 px-3 py-2 text-sm"
              />
            </label>
            <div className="flex items-center gap-2 pt-1">
              <Button type="submit">Create plan</Button>
              <button type="button" onClick={() => setOpen(false)} className="text-sm text-muted-foreground hover:underline">
                Cancel
              </button>
            </div>
          </form>
        </DialogContent>
      </Dialog>
    </>
  );
}
